[project]
name = "order_management_app"
version = "0.1.0"
description = "A simple order management application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
]
[dependency-groups]
dev = [
    "freezegun>=1.5.5",
    "pytest>=9.0.2",
]
